version: '3.8'
services:
    php:
        build: php
        volumes:
            - ./php/app:/app
        env_file:
            - .env
        environment:
            TZ: Asia/Kuala_Lumpur
        command: tail -f /dev/null